-keep class rikka.shizuku.** { *; }
-dontwarn rikka.shizuku.**
-keep class com.maynutlab.astralpatcher.InstallerUserService { *; }
-keep interface com.maynutlab.astralpatcher.IInstallerService { *; }
-keep class com.maynutlab.astralpatcher.IInstallerService$Stub { *; }
-keep class com.maynutlab.astralpatcher.IInstallerService$Stub$Proxy { *; }
