-keep class rikka.shizuku.** { *; }
-dontwarn rikka.shizuku.**
-keep class com.maynutlab.astralpatcher.shizuku.PatchUserService { public <init>(); *; }
-keep interface com.maynutlab.astralpatcher.IPatchService { *; }
-keep class com.maynutlab.astralpatcher.IPatchService$Stub { *; }
-keep class com.maynutlab.astralpatcher.IPatchService$Stub$Proxy { *; }
